version: '3.7'
services:
  app:
    container_name: app
    build: .
    restart: always
    ports:
      - "8001:8000"
#    command: python app/main.py
    command: adev runserver app/main.py --app-factory app_factory
    volumes:
      - .:/app

  mongo:
    restart: always
    image: mongo:4.4
    container_name: mongo
    env_file: .env
    volumes:
        - .data:/data/db
    ports:
        - "${MONGODB_PORT}:${MONGODB_PORT}"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
    command: '--bind_ip_all --port ${MONGODB_PORT}'
