# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import app.grpc_app.auth_pb2 as auth__pb2


class RegistrationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc_app.Channel.
        """
        self.registration = channel.unary_unary(
                '/Registration/registration',
                request_serializer=auth__pb2.UserRequest.SerializeToString,
                response_deserializer=auth__pb2.UserCreatedResponse.FromString,
                )


class RegistrationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def registration(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RegistrationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'registration': grpc.unary_unary_rpc_method_handler(
                    servicer.registration,
                    request_deserializer=auth__pb2.UserRequest.FromString,
                    response_serializer=auth__pb2.UserCreatedResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Registration', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Registration(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def registration(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Registration/registration',
                                                 auth__pb2.UserRequest.SerializeToString,
                                                 auth__pb2.UserCreatedResponse.FromString,
                                                 options, channel_credentials,
                                                 insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
